### ISSUE TITLE
Legacy total progress bar 

### ISSUE THREAD

**Issue by Legoras** [V1P3R-FMG/free-map-genie#14]
It's possible to bring back 'Legacy total progress bar' ?
That function is helpful to show how many points there is at map overall  + easy too see how much at map update was added so.. quite helpful option.

Also ability to check/uncheck all pins at once I hope will be bring back to life :)

Thanks

**Comment by MrFusiion** [comment]
The reason I removed that option was because locations names are also counted as a marker, but you can't mark them.
![image](https://github.com/V1P3R-FMG/free-map-genie/assets/71613276/8be91943-ea23-4770-a49c-d552ce0dabc1)

I was thinking to add them both at the same time, one for the total markers, and then one for the tracked categories.

For the check/uncheck all pins at once buttons. I can bring those back for sure completly forgot about them sry :grimacing:.

**Comment by MrFusiion** [comment]
Your features have been added, After I'm done with the presets fix. I can release the hotfix.
