### ISSUE TITLE
Far Cry 6 - Yara Map

### ISSUE THREAD

**Issue by lucaszfreitasz** [V1P3R-FMG/free-map-genie#3]
After testing the extension on the GOW Ragnarok map, I realized that everything was fine until that moment. The problem came when I noticed that only the Yara map in FC6 was not working any of the features (While the other three maps had no problem). Have any solution about this?

**Comment by MrFusiion** [comment]
I apologize for the delay in responding and for reopening this comment. I just wanted to check if the problem you were experiencing has been resolved or if it is still an issue. If you're still having trouble, I'd be happy to help you further. In order to do so, could you please post a screenshot of your browser console? You can access it by opening the developer tools. Please be sure to remove any sensitive data from the screenshot before sending it. Thank you.
