### ISSUE TITLE
[REQUEST] Refresh button similar to U-Block origin

### ISSUE THREAD

**Issue by BJack0** [V1P3R-FMG/free-map-genie#32]
**Is your feature request related to a problem? Please describe.**
To solve the brave compatibility issue regarding previous issue.

**Describe the solution you'd like**
 Add a refresh button similar to U-Block origin?

**Describe alternatives you've considered**
Add a quick toggle to reload the extension, instead of manually having to do so within the browser manager.

**Comment by MrFusiion** [comment]
#### Issue #28 may be fixed in the next release.
I found a way to make the extension work without DeclarativeNetRequests, but its less reliable as it needs to be loaded before the map.js script gets the chance to do its setup phase.
So I making DNR a option (enable by default) so if somebody's browser doesn't support it or has a buggy implementation they can disable it.
But making DNR optional also means I have to dynamically load the DNR rules which in my test cases also fixes the brave issue not loading the rules.

I still added the reload button though, its a useful feature if other bugs like that show up.

**Comment by MrFusiion** [comment]
Feature is added in the latest release.
If something does not seem right or isn't working you can always reopen this or post a new issue.
