### ISSUE TITLE
Chrome: Failed to build pack

### ISSUE THREAD

**Issue by iZnatOk** [V1P3R-FMG/free-map-genie#4]
The build extension doesn't work
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@3.21.0: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 775 packages, and audited 776 packages in 12s

91 packages are looking for funding
  run `npm fund` for details

23 vulnerabilities (2 low, 10 moderate, 9 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
npm notice
npm notice New minor version of npm available! 9.5.0 -> 9.6.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.0
npm notice Run npm install -g npm@9.6.0 to update!
npm notice

**Comment by MrFusiion** [comment]
My apologies for the delay in responding to your message. I haven't had the opportunity to work on this project for a while. Could you please provide me with the error/output you receive when running the build command? From what I can see, the output you've provided so far seems to be from the `npm install` command.

Alternatively, if you don't wish to modify the code, you could download the pre-built extension from the release section.
[[Latest Release Version]](https://github.com/V1P3R-FMG/free-map-genie/releases/tag/v1.2.0).

I should also note that I was working on building the extension completely through ***webpack*** and ***web-ext***. However, due to my busy school schedule, I'm not sure when I'll be able to push the update. Thank you for your understanding.
