### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by Melechtna** [V1P3R-FMG/free-map-genie#5]
been months since any updates, so, perhaps this isn't being worked on anymore, but with chrome at least, it's no longer functional and you get the message about needing pro for more than 100 markers

**Comment by MrFusiion** [comment]
I apologize for the extension issue and the lack of updates. Currently, I am fully occupied with school and preparing for exams in just two weeks. I was refactoring the code in my free time but it isn't finished yet, hope I can release it as soon as possible.

**Comment by Typ33** [comment]
It seldom works with Brave browser.
Works perfectly fine in chrome for me at least. Never had any issues.
The only feature that it doesn't work with is "**Add note**". After you have used all your 5 notes as free user you will get the following message;
`Error saving note
Request failed with status code 400`

Regardless, even without any updates this is functional.

Thank you for that.
And good luck with your exams.

**Comment by MrFusiion** [comment]
Thanks for letting me know that the extension doesn't work with Brave browser at the moment. Right now, I'm focusing on Chrome and Firefox for testing and refactoring the extension. But don't worry, I'll definitely keep Brave and maybe other browsers in mind for future updates.

The "add note" feature is not currently supported in the extension, The reason is that the extension simulates the backend for some pro features and I have no handler for notes yet, But I can maybe add it during the refactoring process or in a future update.

I have tested the latest version of my extension on chrome, And it works fine for me as well.
@Melechtna, Can you maybe look in the console and see if any error messages popup?

**!! And always make sure if you should send a picture of the console no sensitive data is visible!!**

**Comment by Melechtna** [comment]
> Thanks for letting me know that the extension doesn't work with Brave browser at the moment. Right now, I'm focusing on Chrome and Firefox for testing and refactoring the extension. But don't worry, I'll definitely keep Brave and maybe other browsers in mind for future updates.
> 
> The "add note" feature is not currently supported in the extension, The reason is that the extension simulates the backend for some pro features and I have no handler for notes yet, But I can maybe add it during the refactoring process or in a future update.
> 
> I have tested the latest version of my extension on chrome, And it works fine for me as well. @Melechtna, Can you maybe look in the console and see if any error messages popup?
> 
> **!! And always make sure if you should send a picture of the console that no sensitive data is visible!!**

I would, except, it's suddenly working completely normally in Brave the second I went to go get you the log. Nothing sensitive that I can see in here, so, here's the log if it might still help.

![Screenshot_20230530_081955](https://github.com/V1P3R-FMG/free-map-genie/assets/81296467/29594c8f-b583-4410-ac2d-940cfc35b68a)

As I stated, I tried for maybe, 20 minutes, reinstalled the extension, restarted brave, cleared the site of cookies, etc. Nothing. Went to get you the log, let me blow straight past 100 pins, no issues what so ever. So I have absolutely no idea what changed between my initial report and today.

**Comment by MrFusiion** [comment]
I'm gonna close this issue in favor of the latest release. A new issue can always be posted if it turns out it still doesn't work as intented.
